import React from 'react'

export function GlossaryPage() {
  return (
    <div style={{ display: 'grid', maxWidth: 720 }}>
        <h1>Dice Masters Glossary</h1>
      <p><strong>Abilities:</strong> The text on the die&#x27;s associated card.</p>
      <p><strong>Ability Damage:</strong> Damage from a character&#x27;s ability text (not from its <strong>Attack</strong> stat during combat).</p>
      <p><strong>Action Die:</strong> A die that has no character faces or stats. A face this die that shows a special graphic (such as [ACTION] on a Basic <strong>Action Die</strong>) can be used for a powerful effect.</p>
      <p><strong>Active:</strong> A character is <strong>active</strong> if at least one copy of that character die is in the <strong>Field Zone</strong>. Effects that are applied while a character is <strong>active</strong> don&#x27;t stack for multiple copies of that die in one player&#x27;s <strong>Field Zone</strong>.</p>
      <p><strong>Assign:</strong> To commit your character dice to <strong>attack</strong>, or to <strong>block</strong> an attacking character die. Also, to designate how a character die&#x27;s <strong>Attack</strong> Value is dealt as damage to targets in an <strong>Attack Step</strong>.</p>
      <p><strong>Attack:</strong> To send your characters to try to damage your opponent.</p>
      <p><strong>Attack Zone:</strong> The <strong>Attack Zone</strong> is considered to be a special part of the <strong>Field Zone</strong>. Character dice assigned as attackers or blockers are moved to the <strong>Attack Zone</strong> to distinguish this status, but are always considered to be in the <strong>Field Zone</strong>.</p>
      <p><strong>Burst:</strong> A star-shaped symbol ([BURST]) that indicates extra abilities may be in effect for a die.</p>
      <p><strong>Capture:</strong> When you <strong>capture</strong> a die, move the <strong>captured</strong> die (or dice) to your <strong>Field Zone</strong> and place your capturing die on top of it. The <strong>captured</strong> die no longer exists for game purposes (it may be considered to be &quot;Out of Play&quot;). The <strong>capture</strong> will end when specified in the card text (if unspecified, at the end of the turn), or when the capturing die leaves the <strong>Field Zone</strong> (KO&#x27;d, rerolled to energy, etc.) Once the <strong>capture</strong> ends, return the <strong>captured</strong> die or dice to the place they were <strong>captured</strong> from, on the original level(s).</p>
      <p><strong>Combat Damage:</strong> The damage a character die deals during the <strong>Assign</strong> Damage portion of the <strong>Attack Step</strong> as a result of attacking or blocking.</p>
      <p><strong>Control:</strong> You <strong>control</strong> dice in your <strong>Field Zone</strong>. Also, when an ability (character ability or action die) allows you to take <strong>control</strong> of an opposing die, it becomes yours for game purposes. Move it into your <strong>Field Zone</strong>, and if you have any matching dice of your own then be sure to distinguish it in some way. The <strong>controlled</strong> die will still reference your opponent&#x27;s card, as if you had a &quot;virtual&quot; copy of that card on your team (even if you have a card with the same name on your team). Any modifications to the source card will also affect the <strong>controlled</strong> die and its &quot;virtual&quot; card. If the <strong>controlled</strong> die enters an &quot;unrolled&quot; state (your <strong>Prep Area</strong>, <strong>Used Pile</strong>, etc.) then it immediately goes to your opponent&#x27;s <strong>Prep Area</strong>. Otherwise, if it is still in the <strong>Field Zone</strong> when your <strong>control</strong> ends (at the end of the turn or when the controlling character die leaves the <strong>Field Zone</strong>), return the <strong>controlled</strong> die to your opponent in whatever area you took it from.</p>
      <p><strong>Copy:</strong> <strong>Copying</strong> means that your die takes on the <strong>stats</strong> and/or abilities of another die. If the text says &quot;<strong>copy</strong> the <strong>stats</strong>,&quot; then the <strong>copying</strong> die replaces its own printed <strong>stats</strong> with the printed <strong>stats</strong> on the <strong>copied</strong> die&#x27;s card, for the appropriate level. Your <strong>copying</strong> die also gets to retain its own <strong>burst</strong> symbol and/or <strong>copy</strong> the presence of a <strong>burst</strong> symbol (if applicable). If the text says &quot;<strong>copy</strong> the abilities,&quot; then your <strong>copying</strong> die&#x27;s card would add the <strong>copied</strong> die&#x27;s card text to its own. When this happens, any references the original card text makes to itself would substitute the <strong>copying</strong> die&#x27;s name. If the text says &quot;<strong>copy</strong> the die,&quot; then your die becomes a <strong>copy</strong> of the selected other die for all intents and purposes (the <strong>copy</strong> has all of the names, subtitles, affiliations, abilities, and printed <strong>stats</strong> per level of the original in place of its own). For further information, see these rulings: (1)</p>
      <p><strong>Engaged:</strong> A character die blocking or being blocked is <strong>engaged</strong> with the opposing character die.</p>
      <p><strong>Face:</strong> One side of a die.</p>
      <p><strong>Field:</strong> Paying a character&#x27;s fielding cost (which might be 0) to move them from the <strong>Reserve Pool</strong> to the <strong>Field Zone</strong>. Some other effects will also <strong>field</strong> character dice (but only if the ability explicitly uses the term &quot;<strong>field</strong>&quot;, not &quot;move&quot; or &quot;place&quot; in the <strong>Field Zone</strong>, for example). Character dice <strong>fielded</strong> this way are considered <strong>fielded</strong> for free on level 1, unless specified otherwise.</p>
      <p><strong>Field Zone:</strong> Once rolled to a Character face, dice can be moved here from the <strong>Reserve Pool</strong> by paying their Fielding Cost. Sometimes other effects can &quot;<strong>field</strong>&quot; dice from other areas. Character dice will remain in the <strong>Field Zone</strong> indefinitely until you <strong>attack</strong> with them or another effect sends them elsewhere. Some special Action Dice may also be used by placing them in the <strong>Field Zone</strong>. The <strong>Attack Zone</strong> is considered to be a special part of the <strong>Field Zone</strong>.</p>
      <p><strong>Founder:</strong>This keyword notes that a character founded their team, it can&#27;t be ignored</p>
      <p><strong>Global Ability:</strong> A game effect denoted within the text box of a card by the keyword &quot;<strong>Global:</strong>&quot; the effect happens if the prerequisite cost is paid for. A <strong>Global Ability</strong> is available for both players to use even if they do not have that die available for them to purchase, and the character or action whose card the <strong>Global</strong> is printed on does not need to be <strong>active</strong>.</p>
      <p><strong>Opposing:</strong> <strong>Controlled</strong> by another player (either because it belongs to them, or they&#x27;ve taken <strong>control</strong> of one of your dice).</p>
      <p><strong>Out of Play:</strong> This is a special area that is not represented on the playmat. When you spend Energy during your turn, or use an <strong>Action Die</strong>, it goes <strong>Out of Play</strong> until the end of the turn when it is moved to the <strong>Used Pile</strong>. Dice that are <strong>Out of Play</strong> cannot be interacted with by any game mechanics, and will not be used to refill the bag if it runs out mid-turn. Unblocked attackers also go <strong>Out of Play</strong>, as well as any dice sent from the <strong>Field</strong> or <strong>Reserve Pool</strong> &quot;to the <strong>Used Pile</strong>&quot; during your turn. The <strong>Out of Play</strong> area does not exist during your opponent&#x27;s turn, and any Energy spent or dice sent to the <strong>Used Pile</strong> will go directly there.</p>
      <p><strong>Prep:</strong> Move a die from the specified area to the <strong>Prep Area</strong>. If this is from your bag, randomly draw one and place it in your <strong>Prep Area</strong>.</p>
      <p><strong>Prep Area:</strong> Dice that are here before your turn will be added to the 4 dice you draw at the beginning of your turn, and all those dice will be rolled during your Roll and Reroll Step. Character dice that are KO&#x27;d go to the <strong>Prep Area</strong>, and certain game effects will direct you to &quot;<strong>Prep</strong> a die&quot; – meaning add the specified die to your <strong>Prep Area</strong>.</p>
      <p><strong>Reroll:</strong> Many powers allow you to &quot;<strong>reroll</strong>&quot; one or more rolled dice (in the <strong>Field Zone</strong> or your <strong>Reserve Pool</strong>). When you <strong>reroll</strong> a die, it remains in the same area it was in unless (a) otherwise specified by the card text for the resulting face, or (b) it&#x27;s in a location that the die face cannot be (for example, an energy result in the <strong>Field Zone</strong>). If the die face cannot be in the specified location and its fate is not specified in the card text, move the die to the <strong>Reserve Pool</strong>. <strong>Rerolling</strong> a <strong>fielded</strong> Character Die to a different Character face means it remains in the <strong>Field Zone</strong> on its new face and never &quot;left the <strong>Field Zone</strong>&quot; (and will therefore not trigger any &quot;when <strong>fielded</strong>&quot; effects). <strong>Rerolling</strong> a <strong>fielded</strong> <strong>Continuous</strong> <strong>Action Die</strong> to an energy face will result in it leaving the <strong>Field Zone</strong> and moving to the <strong>Reserve Pool</strong>. If a <strong>fielded</strong> character die is <strong>rerolled</strong> to energy and leaves the <strong>Field Zone</strong>, it loses any applied or persistent effects that had been given to it (stat modifiers, granted affiliations, must <strong>attack</strong>, etc.).</p>
      <p><strong>Reserve Pool:</strong> After your Roll and Reroll Step, all the dice are placed in the <strong>Reserve Pool</strong> and used from here. Energy can be spent, Action Dice can be used, and Character Dice can be <strong>fielded</strong> from here. During your opponent&#x27;s turn, only Energy dice can be in the <strong>Reserve Pool</strong>, and are cleared during your following Clear and Draw Step. If an effect ever tells you to &quot;draw a die&quot; without specifying what to do with it, you should roll it a single time and place it in the <strong>Reserve Pool</strong> on the resulting face.</p>
      <p><strong>Sidekick:</strong> <strong>Sidekick</strong> Dice are special dice that each player begins the game with. You can never gain any more, or get rid of the ones you have. They can provide any of the energy types, or even Wild ([?]) energy. They also have one character face with the ([PAWN]) custom icon, and <strong>stats</strong>. When they are rolled to this face (in the <strong>Reserve Pool</strong> or the <strong>Field Zone</strong>) they are considered to be <strong>Sidekick</strong> Character Dice (level 1), for game effects that look for character dice. However, when they are unrolled (in the <strong>Prep Area</strong>, <strong>Used Pile</strong>, or the bag) they are not considered to be character dice, but just <strong>Sidekick</strong> dice. For any game effects that care, they are considered to have a Purchase Cost of 0. Any card effects that refer to [PAWN] refer to rolled <strong>Sidekick</strong> Character Dice on their [PAWN] face (usually in the <strong>Field Zone</strong>).</p>
      <p><strong>Spin:</strong> To turn or rotate a die so that it shows a different face.</p>
      <p><strong>Stats:</strong> The numbers on a character die face (fielding cost, <strong>attack</strong>, and defense).</p>
      <p><strong>Swap:</strong> Some abilities allow you to &quot;<strong>swap</strong>&quot; two dice (usually character dice, though not always). When you do so, you take the two dice and change their positions exactly. If a character die is attacking (blocked or unblocked) or blocking and it is <strong>swapped</strong> for a different character die, that newly <strong>swapped</strong> in die will also be attacking or blocking in the same position. If a character die in the <strong>Field Zone</strong> is <strong>swapped</strong> with a character die in the <strong>Used Pile</strong>, it will change positions exactly and not go <strong>Out of Play</strong>. Dice that are <strong>swapped</strong> from an &quot;unrolled&quot; position (such as the <strong>Used Pile</strong>) to a &quot;rolled&quot; position&quot; (such as the <strong>Field Zone</strong>) will be put on their level 1 side unless otherwise specified. This does not count as fielding that die. If a character die has a persistent effect on it that will cause it to return to its card at the end of the turn, it is not a valid target to be <strong>swapped</strong> out.</p>
      <p><strong>Tokens (Character):</strong> Some cards will have the ability to generate character &quot;<strong>tokens</strong>.&quot; These <strong>tokens</strong> may be represented by whatever you would like, and for game purposes are considered to be level 1 character dice with a purchase cost of 0. Their A and D values will be given by the card generating them, and they can only exist in the <strong>Field Zone</strong>. As soon as they leave the <strong>Field Zone</strong> they no longer exist. They may not be spun up, spun down, or <strong>rerolled</strong>. They do not have an energy type.</p>
      <p><strong>Used Pile:</strong> This is where dice you use end up. At the end of your turn, all dice that are <strong>Out of Play</strong> are moved to the <strong>Used Pile</strong>. Purchased dice are also placed directly in the <strong>Used Pile</strong>, along with un<strong>fielded</strong> character dice after your Main Step. Any Energy spent on your opponent&#x27;s turn goes directly to the <strong>Used Pile</strong>, along with remaining energy cleared from your <strong>Reserve Pool</strong> during the Clear and Draw Step. When you need to draw one or more dice, and your bag is empty, you refill it will all dice in your <strong>Used Pile</strong> (not including any dice that are <strong>Out of Play</strong>) and continue drawing. This is how the dice you purchase will eventually cycle through your bag to be rolled and used.</p>
      <p><strong>When Fielded:</strong> An effect that takes place when you pay a character&#x27;s fielding cost to move it to the <strong>Field Zone</strong>, or an ability explicitly allows you to &quot;<strong>field</strong>&quot; (not &quot;move,&quot; &quot;place,&quot; &quot;return,&quot; or &quot;<strong>swap</strong>&quot; a die into the <strong>Field Zone</strong>) a die from a different location. These abilities take place once for each copy of that die you <strong>field</strong>.</p>
      <p><strong>While Active:</strong> See <strong>Active</strong>.</p>
    </div>
  )
}
