import React from 'react'

export function KeywordsPage() {
  return (
    <div style={{ display: 'grid', maxWidth: 720 }}>
      <h1>Keywords</h1>
      <p><strong>Adventurer:</strong> Any character with the <strong>Experience</strong> ability. (DDDM1)</p>
      <p><strong>Aftershock:</strong> When this character leaves the Field Zone because of your opponent (damage from their characters or actions, getting KO&#x27;d, being removed from the game, sent to the Used Pile or Reserve Pool) you must use their <strong>Aftershock</strong> effect. (MDM4)</p>
      <p><strong>Ally:</strong> Character dice with the <strong>Ally</strong> ability count as [PAWN] while in the Field Zone in addition to their other designations. They don&#x27;t count as Sidekick Dice while in the bag, Prep Area, Used Pile, or anywhere else. (MDM4)</p>
      <p><strong>Amplify:</strong> When you use an Action Die, spin each character die with <strong>Amplify</strong> up one level (if able). (MDM10)</p>
      <p><strong>Anti-Breath Weapon:</strong> When a character die with <strong>Breath Weapon</strong> X attacks, you may pay X energy to prevent that damage. (DDDM2)</p>
      <p><strong>Attune:</strong> While a character you control with <strong>Attune</strong> is active, when you use an action die, that character deals 1 damage to target player or character die (no matter how many of that character&#x27;s dice are active). (DDDM3)</p>
      <p><strong>Awaken:</strong> When a die with <strong>Awaken</strong> spins up 1 or more levels, you may use its <strong>Awaken</strong> effect. You get to use the effect for each individual die that spins up, so if you have two copies of the same die active and they both spin up, you will get two instances of the effect. (MDM8)</p>
      <p><strong>Back for More:</strong> When a die with <strong>Back for More</strong> begins the turn in your Prep Area, and is rolled during the Roll and Reroll Step, use its <strong>Back for More</strong> effect (this isn&#x27;t optional). (MDM 6)</p>
      <p><strong>Boomerang:</strong> Action dice with <strong>boomerang</strong> are re-rolled after they&#x27;re used. If they reveal an action face, add them to your Prep Area. (DCDM 5)</p>
      <p><strong>Breath Weapon X:</strong> When a character die with <strong>Breath Weapon X</strong> attacks, you may pay <strong>X</strong> energy. Deal <strong>X</strong> damage to your opponent and all of their character dice. You may use multiple <strong>Breath Weapons</strong> in a turn, but only one per character (no matter how many copies of that die are attacking). (DDDM1)</p>
      <p><strong>Call Out:</strong> When a character die with <strong>Call Out</strong> attacks, you target an opposing character die. The targeted die can only legally block the attacking die that used <strong>Call Out</strong> on it, and no other die can legally block the die that used <strong>Call Out</strong>. If the die that used <strong>Call Out</strong> cannot legally be blocked for any reason (an effect made it unblockable, two different dice chose the same target for their <strong>Call Out</strong>, the die targeted with <strong>Call Out</strong> was KO&#x27;d, etc.) then the effect of <strong>Call Out</strong> is cancelled. (MDM7)</p>
      <p><strong>Cleave:</strong> If a die with <strong>Cleave</strong> attacks and KOs a blocking character die with combat damage, they deal half of their A (rounded down) to another character die your opponent controls as combat damage (only once). (DDDM2)</p>
      <p><strong>Common Ground:</strong> When a character die with <strong>Common Ground</strong> attacks with at least one [VILLAINS] character die, you get to use the character die&#x27;s <strong>Common Ground</strong> ability. (DCDM5)</p>
      <p><strong>Continuous:</strong> Actions with <strong>Continuous</strong> are &quot;used&quot; by moving them to the Field Zone. They can stay there past the end of the turn. Usually they&#x27;ll either send themselves to the Used Pile for an effect, or allow you to send them whenever you could use a Global Ability. If they are sent to the Used Pile while you are the active player, they go Out of Play first. As with all non-character dice, <strong>Continuous</strong> dice cannot attack or block. (DCDM2)</p>
      <p><strong>Corrupt X:</strong> Target player draws <strong>X</strong> dice from their bag (refilling from the Used Pile if necessary). You choose one die (no matter how many dice are drawn) and place it in that player&#x27;s Used Pile, and the rest are returned to the bag. (MDM11)</p>
      <p><strong>Crossover:</strong> <strong>Crossover</strong> characters have two or more types of energy. To purchase them you&#x27;ll need to spend at least one of each type of energy they require. You won&#x27;t be able to reduce their cost to avoid paying each type of energy to purchase their dice. They count as every type of energy you must spend to purchase their die. (DCDM4)</p>
      <p><strong>Crosspulse:</strong> <strong>Crosspulse</strong> is a special version of <strong>Impulse</strong> found only on <strong>Crossover</strong> Characters. When you purchase them by only spending their matching type(s) of energy, you get to use their <strong>Crosspulse</strong> ability. (DCDM4)</p>
      <p><strong>Deadly:</strong> At the end of the turn, character dice that were engaged with a character die that has <strong>Deadly</strong> are KO&#x27;d (even if the character with <strong>Deadly</strong> has been KO&#x27;d or leaves the Field Zone). (MDM6)</p>
      <p><strong>Energize:</strong> Whenever you roll this die on one of its double energy faces, you must use its <strong>Energize</strong> effect (this isn&#x27;t optional). During the Roll and Reroll Step, only check at the end of the Step. The character with <strong>Energize</strong> does not need to be active for the ability to trigger. (MDM11)</p>
      <p><strong>Energy Drain:</strong> After blockers are assigned, spin each character engaged with a character die with <strong>Energy Drain</strong> down one level. Character dice at level 1 can&#x27;t be spun down. (DDDM1)</p>
      <p><strong>Enlistment:</strong> <strong>Enlistment</strong> effects let you get extra effects unless your opponent KOs one of their character dice. (MDM5)</p>
      <p><strong>Equip:</strong> Gear dice with the <strong>Equip</strong> keyword may be attached to a character with the [GEAR] icon immediately below their alignment icon when they first enter the Field Zone, and at the beginning of each player&#x27;s turn. You may switch the attachment from one character die to another. If the equipped character die leaves the Field Zone, the Gear die remains in the Field Zone (unattached). (DDDM1)</p>
      <p><strong>Experience:</strong> A character die with the <strong>Experience</strong> keyword is considered an <strong>Adventurer</strong>. At the end of your turn, if you KO&#x27;d at least one opposing [MONSTER] during your turn, all <strong>Adventurers</strong> who were active during the KO and remain active at the end of the turn gain one <strong>Experience Token</strong> on their card. A card can only gain one <strong>Experience Token</strong> per turn from the <strong>Experience</strong> keyword (though other abilities may allow a card to gain more than one). An opposing player KOing their own Monster will not generate <strong>Experience Tokens</strong>, nor can you gain an <strong>Experience Token</strong> by KOing one of your own Monsters. (DDDM1)</p>
      <p><strong>Experience Token:</strong> <strong>Experience Tokens</strong> are placed on character cards. Each token grants +1A and +1D to all character dice belonging to that card. <strong>Experience Tokens</strong> will still provide their bonus even if that card&#x27;s text is being ignored. (DDDM1)</p>
      <p><strong>Fabricate X-Y:</strong> Characters with <strong>Fabricate</strong> will have 2 numbers (X-Y). If you KO exactly X character dice with a total combined purchase cost of Y or more, you can purchase the die with <strong>Fabricate</strong> X-Y for free. This can only be done when you could normally purchase a character die (generally during your own Main Step). [PAWN] are considered to have a purchase cost of 0. (DDDM 2)</p>
      <p><strong>Fast:</strong> Characters with <strong>Fast</strong> deal combat damage before other characters, all at the same time, instead of at the regular time for combat damage. (DDDM2)</p>
      <p><strong>Flip:</strong> Cards with the <strong>Flip</strong> keyword have a different face on each physical side of the card (front and back). All dice you control are represented by the face up side of your card with the <strong>Flip</strong> keyword, regardless of which face the card was on previously. At the beginning of each of your turns, you may flip any card with <strong>Flip</strong> to its other face. There also may be game effects that direct you to flip cards. Only cards with two faces may be flipped. (DCDM5)</p>
      <p><strong>Founder:</strong> This keyword notes that a character founded their team, it can’t be ignored.</p>
      <p><strong>Frag:</strong> When a character die with <strong>Frag</strong> attacks and KO&#x27;s one or more blocking character dice with combat damage, deal 1 damage to all opposing character dice that didn&#x27;t block this turn (before damage is cleared). (WHDM1)</p>
      <p><strong>Fusion:</strong> During your Main Step, you may move a number of appropriate fusion material monsters (denoted on the card) from your Field Zone to your Prep Area. Move the die with <strong>Fusion</strong> from its card to the Prep Area. (YGO1)</p>
      <p><strong>Gadgeteer:</strong> When a character die with <strong>Gadgeteer</strong> attacks, you may roll a <strong>Continuous</strong> action die (including <strong>Gear</strong> or <strong>Traps</strong>) that is in your Used Pile. If you roll a non-energy face, you may move it into your Field Zone. Otherwise, return it to your Used Pile. (DCDM5)</p>
      <p><strong>Gate:</strong> When you field a die with <strong>Gate</strong>, you may take an unpurchased, qualifying die from one of your cards and roll it. On a character face, you can place the unpurchased die into your Prep Area. (DDDM 2)</p>
      <p><strong>Gear:</strong> <strong>Gear</strong> are a special type of <strong>Continuous</strong> Action Dice that have the <strong>Equip</strong> keyword. They are &quot;used&quot; by moving them into the Field Zone. When you initially do this, and at the beginning of each turn that this die is active (any player&#x27;s turn), you may attach this die to a character with the Equip icon ([GEAR]). You may switch the attachment from one character die to another. If the equipped character die leaves the Field Zone, the <strong>Gear</strong> die remains in the Field Zone (unattached). As with all non-character dice, <strong>Gear</strong> dice can&#x27;t attack or block. (DDDM1)</p>
      <p><strong>Heroic:</strong> Dice with <strong>Heroic</strong> can pair up with other dice (different character) that you control that have the <strong>Heroic</strong> ability. Place paired up dice side by side. <strong>Heroic</strong> takes place at the same time a character is fielded. Dice may only be paired up with one other die (the new partner replaces the old one). They attack and block separately. (MDM2)</p>
      <p><strong>Impulse:</strong> <strong>Impulse</strong> abilities happen when you purchase a character die with the <strong>Impulse</strong> ability. The character does not need to be already active to use the <strong>Impulse</strong> ability. (DCDM4)</p>
      <p><strong>Iron Will:</strong> This character cannot be KO&#x27;d unless it was previously damaged this turn or if it is simultaneously damaged by two different sources. If this character was previously damaged this turn and (a) it is damaged a second time and the total damage it received this turn equals or exceeds its D, or (b) a game effect later in the same turn reduces this character&#x27;s defense such that the damage it previously received this turn is equal to or greater than its new D, or (c) a later game effect this turn directs that the character be KO&#x27;d, then KO this character. Also KO this character if it is simultaneously damaged by more than one source (for example, being blocked by more than one character die) and the total damage it receives from those sources equals or exceeds its D. Characters with <strong>Iron Will</strong> (that have not been damaged) may not be selected to pay a cost that requires you to KO a character. (DCDM3)</p>
      <p><strong>Immortal:</strong> When a character die with <strong>Immortal</strong> would go to the Used Pile (not being fielded at the end of the Main Step, attacking and being unblocked, being Sacrificed, etc.), instead add that character die to its owner&#x27;s bag. Character dice with <strong>Immortal</strong> that went Out of Play this turn go to the Bag at the end of the turn instead of the Used Pile. This does not apply to dice initially being purchased, dice being swapped, or dice being spent as energy. (MDM9)</p>
      <p><strong>Infiltrate:</strong> When a character die with <strong>Infiltrate</strong> attacks and is not blocked, you may choose to remove that character die from combat (immediately after blockers are declared, before Action dice or Global Abilities may be used). If you do, that character die deals 1 damage to your opponent, and the die remains in your Field Zone. (MDM7)</p>
      <p><strong>Intimidate:</strong> When fielded, remove target opposing character die from the Field Zone until end of turn. Place it next to your character cards during that turn as a reminder. (MDM5)</p>
      <p><strong>Loyalty: Loyalty</strong> Counters stay on a character card and give those dice +1A and +1D for each Loyalty Counter.</p>
      <p><strong>Obscure:</strong> When you use an Action die, this character is unblockable until end of turn. (DDDM4)</p>
      <p><strong>Overcrush:</strong> When attacking, if this character KOs all of its blockers (or they are removed for other reasons), it deals any remaining damage to your opponent. (DCDM1)</p>
      <p><strong>Range X:</strong> When one or more character dice with <strong>Range</strong> attack, each active character die with <strong>Range</strong> (on both sides) simultaneously deals damage equal to its <strong>Range</strong> value <strong>(X)</strong> to target opposing character die. Each character die with <strong>Range</strong> may choose a different target, and the defending player still resolves their <strong>Range</strong> damage even if the <strong>Range</strong> die was KO&#x27;d by the active player&#x27;s <strong>Range</strong> damage. All <strong>Range</strong> damage is dealt simultaneously; the active player chooses their targets and resolves the damage, immediately followed by the inactive player choosing their targets and resolving the damage. (WHDM1)</p>
      <p><strong>Recruit:</strong> When a character die with the <strong>Recruit</strong> keyword damages an opponent with combat damage, you may move a die that matches what is listed in the ability from your Used Pile, Reserve Pool, or Prep Area into the Field Zone on its level 1 character face. For example, it could match a character&#x27;s name (exactly), affiliation, energy type, or Sidekick die type. A matching die in the Reserve Pool may be spun from an energy face to its level 1 character face. (MDM12)</p>
      <p><strong>Regenerate:</strong> If this character would be KO&#x27;d, roll it. If you roll a character face, return it to the field on the rolled face (but not the Attack Zone) and clear all damage from it. Otherwise, it is KO&#x27;d and moved to your Prep Area. If a character die successfully <strong>Regenerates</strong>, it does not trigger any &quot;When KO&#x27;d&quot; effects, and any applied modifiers (stat boosts, granted affiliations, etc.) remain. (DDDM1)</p>
      <p><strong>Resistance:</strong> <strong>Resistance</strong> effects let you get extra effects if one of your character dice was KO&#x27;d this turn. (MDM5)</p>
      <p><strong>Retaliation:</strong> If character you control with <strong>Retaliation</strong> is active, and character die you control that shares an affiliation with it is KO&#x27;d (including another copy of the die with <strong>Retaliation</strong>), deal 1 damage to an opposing player. A character die cannot trigger its own <strong>Retaliation</strong> since it is no longer active then. (DCDM1)</p>
      <p><strong>Ritual:</strong> Instead of paying this monster&#x27;s Fielding Cost you may send a monster [character] die from your Reserve Pool to Out of Play in order to field this monster. (YGO1)</p>
      <p><strong>Rush:</strong> If you draw this die during your Clear and Draw step, draw and roll an extra die for each die of the indicated type drawn during that step. (MDM13)</p>
      <p><strong>Sacrifice:</strong> <strong>Sacrificed</strong> characters are moved from the Field Zone to the Used Pile (often as a cost or penalty). If one of your character dice is sacrificed while you are the active player, it goes Out of Play first. (MDM4)</p>
      <p><strong>Spark:</strong> While a character with a <strong>Spark</strong> ability is active, if you roll a [BURST] face on one or more dice, use the <strong>Spark</strong> ability at the end of the current Step. During the Roll and Reroll Step, only check at the end of the Step. (DDDM4)</p>
      <p><strong>Strike:</strong> On the turn you field this, at the end of the Main Step, if you fielded no other character dice this turn, this character die gets +2A, +2D, and <strong>Overcrush</strong>. (DCDM6)</p>
      <p><strong>Stun Tokens:</strong> Certain abilities let you place <strong>Stun tokens</strong> on cards. While a card has a <strong>Stun token</strong> on it, its dice cannot attack or block. The owner of a card with a <strong>Stun token</strong> on it may pay [2] at any time they could use a Global Ability to remove one <strong>Stun token</strong> from that card. (DCDM5)</p>
      <p><strong>Suit Up:</strong> When you purchase a character die with the <strong>Suit Up</strong> keyword, you may KO a character you control whose name matches one of those listed in the ability. If you do, you may immediately field the purchased die at level 2. For example, if you purchased a character die with <strong>Suit Up</strong> Iron Man, you may immediately KO an Iron Man character die to immediately field the purchased character die at level 2.(MDM2017)</p>
      <p><strong>Swarm:</strong> While a die with <strong>Swarm</strong> is active, and you draw another copy of that die from your bag during your Clear and Draw Step, draw an extra die from your bag and add it to your Roll and Reroll. This may trigger multiple times if you keep drawing multiple copies of dice with <strong>Swarm</strong>. (DDDM1)</p>
      <p><strong>Synergy:</strong> While a character with <strong>Synergy</strong> is active, you can pay the cost of their <strong>Synergy</strong> ability to use it. You could use it as the same time as you would a Global Ability. (DCDM4)</p>
      <p><strong>Tag Out:</strong> After blockers are declared, you may Prep this die from the Field Zone to give target character die +2A and +2D until end of turn. (WWEDM1)</p>
      <p><strong>Teamwatch:</strong> When a character with <strong>Teamwatch</strong> is active and you field another character die with the same affiliation, use their <strong>Teamwatch</strong> ability. (MDM3)</p>
      <p><strong>Teamwork:</strong> <strong>Teamwork</strong> abilities will let you get extra effects from actions when you have multiple character dice with the same affiliation. (MDM3)</p>
      <p><strong>Traps:</strong> <strong>Traps</strong> are a special kind of <strong>Continuous</strong> action dice that move to the Field Zone when used, and stay there until Triggered. When the criteria of the Trap die&#x27;s Trigger is met, you must immediately send the die to your Used Pile to use its Effect. If the Trap is triggered while you are the active player, it goes Out of Play first. (DDDM3)</p>
      <p><strong>Turtle Power:</strong> While a character with <strong>Turtle Power</strong> is active, all other character dice with the [TURTLES] affiliation cost [1] energy less to purchase for each active (unique) character with <strong>Turtle Power</strong> you control. (TMNT1)</p>
      <p><strong>Underdog:</strong> This ability can be used when you have fewer character dice fielded than your opponent. Sometimes the character won&#x27;t need to be active (it may affect how the character is purchased or fielded). If an <strong>Underdog</strong> effect would trigger when a die is fielded, it counts the newly fielded die when determining if you have fewer dice. (MDM4)</p>
      <p><strong>Vengeance:</strong> <strong>Vengeance</strong> effects take place when you (the player) is dealt damage, and the character with <strong>Vengeance</strong> is active. (DCDM3)</p>
    </div>
  )
}
